### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jonathantneal**
- Bumps major versions of postcss, blue-tape, del, and path-exists
- Resolves PostCSS compatibility issue (`Your current PostCSS version is 6.0.14, but postcss-assets-rebase uses 4.1.16...`)
- All tests remain functional

### CODE REVIEW

**Comment by cakeinpanic** [comment]
@jonathantneal checks have failed, fix it please

**Comment by jonathantneal** [comment]
@cakeinpanic, your wish is my command. Your .travis.yml has now been updated.

PostCSS follows the Node LTS model, and has therefore ended support for Node v0.12, while it continues support for Node v4. Further details are available at https://github.com/nodejs/Release

**Comment by jonathantneal** [comment]
Curiously, one of your `devDependencies` now requires `tape` whereas it must have previously included it itself. This has been corrected. Behold: _green_!

**Comment by cakeinpanic** [comment]
thank you!

**Pull request merged**
