### PR TITLE
Replace reduce-function-call with postcss-value-parser

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by cakeinpanic** [comment]
Thank you!

**Comment by cakeinpanic** [comment]
Wow, thank you, postcss-value-parser is way better than reduceFunctionCall!

**Comment by cakeinpanic** [comment]
There are conflicts after your previous PR merge, please, resolve them

**Comment by TrySound** [comment]
@cakeinpanic Done

**Pull request merged**
